[package]
name = "input"
version = "0.1.0"
edition = "2021"

[features]
force-soft = ["sha2/force-soft"]

[dependencies]
bytemuck = { version = "1.13.0", features = ["derive"] }
sha2 = { version = "0.10.6", default-features = false }
