[package]
name = "supervisor-services"
version = "0.1.0"
edition = "2021"

[features]
default = ["supervisor", "kernel"]
supervisor = []
kernel = []

[dependencies]
bit_field = "0.10.2"
bytemuck = { version = "1.15.0", features = ["derive"] }
constants = { workspace = true }
