extend = "../tee/Makefile.toml"

[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.default]
alias = "build"

[tasks.build]
dependencies = ["build-tee", "build-mushroom"]

[tasks.build-mushroom]
dependencies = ["build-mushroom-development", "build-mushroom-production"]

[tasks.build-mushroom-development]
condition = { profiles = ["development", "kasan"] }
command = "cargo"
args = ["build", "-p", "mushroom", "--features", "bin"]

[tasks.build-mushroom-production]
condition = { profiles = ["production", "profiling"] }
command = "cargo"
args = ["build", "-p", "mushroom", "--features", "bin", "--release"]

[tasks.run]
dependencies = ["run-development", "run-kasan", "run-production", "run-profiling"]

[tasks.run-development]
condition = { profiles = ["development"] }
dependencies = ["build"]
script = "target/debug/mushroom $@"
[tasks.run-development.env]
SUPERVISOR = "../tee/target/supervisor/supervisor/supervisor"
KERNEL = "../tee/target/x86_64-unknown-none/kernel/kernel"

[tasks.run-kasan]
condition = { profiles = ["kasan"] }
dependencies = ["build"]
script = "target/debug/mushroom $@"
[tasks.run-kasan.env]
SUPERVISOR = "../tee/target/supervisor/supervisor/supervisor"
KERNEL = "../tee/target/x86_64-unknown-none/kernel/kernel"
KASAN = true

[tasks.run-production]
condition = { profiles = ["production"] }
dependencies = ["build"]
script = "target/release/mushroom $@"
[tasks.run-production.env]
SUPERVISOR = "../tee/target/supervisor/supervisor-release/supervisor"
KERNEL = "../tee/target/x86_64-unknown-none/kernel/kernel"

[tasks.run-profiling]
condition = { profiles = ["profiling"] }
dependencies = ["build"]
script = "target/release/mushroom $@"
[tasks.run-profiling.env]
SUPERVISOR = "../tee/target/supervisor/supervisor/supervisor"
KERNEL = "../tee/target/x86_64-unknown-none/kernel-profiling/kernel"
PROFILE_FOLDER = "uftrace.data"

[tasks.test]
dependencies = ["test-amd64", "test-i386"]

[tasks.test-amd64]
dependencies = ["test-amd64-development", "test-amd64-kasan", "test-amd64-production"]

[tasks.test-amd64-development]
condition = { profiles = ["development"] }
dependencies = ["build"]
command = "cargo"
args = ["test", "--target", "x86_64-unknown-linux-musl", "-p", "tests"]
cwd = "../tee"
[tasks.test-amd64-development.env]
SUPERVISOR = "../target/supervisor/supervisor/supervisor"
KERNEL = "../target/x86_64-unknown-none/kernel/kernel"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUNNER = "../host/target/debug/mushroom run --input /dev/null --output /dev/null --attestation-report /dev/null --init"

[tasks.test-amd64-kasan]
condition = { profiles = ["kasan"] }
dependencies = ["build"]
command = "cargo"
args = ["test", "--target", "x86_64-unknown-linux-musl", "-p", "tests"]
cwd = "../tee"
[tasks.test-amd64-kasan.env]
SUPERVISOR = "../target/supervisor/supervisor/supervisor"
KERNEL = "../target/x86_64-unknown-none/kernel/kernel"
KASAN = true
CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUNNER = "../host/target/debug/mushroom run --input /dev/null --output /dev/null --attestation-report /dev/null --init"

[tasks.test-amd64-production]
condition = { profiles = ["production"] }
dependencies = ["build"]
command = "cargo"
args = ["test", "--target", "x86_64-unknown-linux-musl", "-p", "tests"]
cwd = "../tee"
[tasks.test-amd64-production.env]
SUPERVISOR = "../target/supervisor/supervisor-release/supervisor"
KERNEL = "../target/x86_64-unknown-none/kernel/kernel"
CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUNNER = "../host/target/release/mushroom run --input /dev/null --output /dev/null --attestation-report /dev/null --init"

[tasks.test-i386]
dependencies = ["test-i386-development", "test-i386-kasan", "test-i386-production"]

[tasks.test-i386-development]
condition = { profiles = ["development"] }
dependencies = ["build"]
command = "cargo"
args = ["test", "--target", "i686-unknown-linux-musl", "-p", "tests"]
cwd = "../tee"
[tasks.test-i386-development.env]
SUPERVISOR = "../target/supervisor/supervisor/supervisor"
KERNEL = "../target/x86_64-unknown-none/kernel/kernel"
CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUNNER = "../host/target/debug/mushroom run --input /dev/null --output /dev/null --attestation-report /dev/null --init"

[tasks.test-i386-kasan]
condition = { profiles = ["kasan"] }
dependencies = ["build"]
command = "cargo"
args = ["test", "--target", "i686-unknown-linux-musl", "-p", "tests"]
cwd = "../tee"
[tasks.test-i386-kasan.env]
SUPERVISOR = "../target/supervisor/supervisor/supervisor"
KERNEL = "../target/x86_64-unknown-none/kernel/kernel"
KASAN = true
CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUNNER = "../host/target/debug/mushroom run --input /dev/null --output /dev/null --attestation-report /dev/null --init"

[tasks.test-i386-production]
condition = { profiles = ["production"] }
dependencies = ["build"]
command = "cargo"
args = ["test", "--target", "i686-unknown-linux-musl", "-p", "tests"]
cwd = "../tee"
[tasks.test-i386-production.env]
SUPERVISOR = "../target/supervisor/supervisor-release/supervisor"
KERNEL = "../target/x86_64-unknown-none/kernel/kernel"
CARGO_TARGET_I686_UNKNOWN_LINUX_MUSL_RUNNER = "../host/target/release/mushroom run --input /dev/null --output /dev/null --attestation-report /dev/null --init"

[tasks.clean]
dependencies = ["clean-tee"]
command = "cargo"
args = ["clean"]
