pub const VMEXIT_REASON_CPUID_INSTRUCTION: u32 = 10;
pub const VMEXIT_REASON_HLT_INSTRUCTION: u32 = 12;
pub const VMEXIT_REASON_VMCALL_INSTRUCTION: u32 = 18;
pub const VMEXIT_REASON_MSR_WRITE: u32 = 32;
