[package]
name = "mushroom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
bitflags = "1.3.2"
bit_field = "0.10.1"
bytemuck = { version = "1.13.0", features = ["derive", "min_const_generics", "extern_crate_std"] }
constants = { workspace = true }
loader = { workspace = true }
nix = "0.26.1"
snp-types = { workspace = true }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
volatile = { git = "https://github.com/Freax13/volatile", rev = "d7c0373", features = ["unstable"] }
x86_64 = { git = "https://github.com/rust-osdev/x86_64", rev = "bae6119533f19cd5c3557d5a302524f1d72456c5" }
libc = "0.2.146"
