[package]
name = "profiler-types"
version = "0.1.0"
edition.workspace = true

[dependencies]
bytemuck = { version = "1.15.0", features = ["derive", "min_const_generics"] }
constants = { workspace = true }
