[workspace]
members = ["constants", "io", "loader", "profiler-types", "snp-types"]
resolver = "2"

[workspace.dependencies]
constants = { path = "constants" }
io = { path = "io" }
snp-types = { path = "snp-types" }
