[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
constants = { workspace = true }
bit_field = "0.10.1"
bytemuck = { version = "1.13.0", features = ["min_const_generics"] }
goblin = "0.6.0"
io = { workspace = true }
itertools = { version = "0.10.5", default-features = false }
snp-types = { workspace = true }
thiserror = { version = "1.0.37" }
raw-cpuid = "10.6.0"
x86_64 = { git = "https://github.com/rust-osdev/x86_64", rev = "bae6119533f19cd5c3557d5a302524f1d72456c5" }
